### ISSUE TITLE
Materials not found

### ISSUE THREAD

**Issue by douglase** [jordens/rayopt-notebooks#1]
This looks like a great project!

I've tried both the anaconda install  and the current master of rayopt and _python setup.py tests_ runs fine with both but many of the examples gives errors like:

focuser.ipynb:

```
 "KeyError: u'material None/schott/n-bk7 not found'.
 "KeyError: u'material None/glass/lithosil-q not found". 
```

catadioptric_microscope_US7502177B2 L.ipynb:

```
 material not found SUPRASIL __init__() got an unexpected keyword argument 'vd' 
```

the Hubble telescope and the regular tutorial ran, and if I replace the materials above with "glass/SCHOTT-BK|N-BK7" the examples start to run.

Do these demos only run if the OSLO and Zemax materials are installed or has the notation for referencing materials changed? (also, is there a function to print a list of available materials?)

**Comment by jordens** [comment]
Yes. Those examples use materials (and lenses) from the Oslo/Zemax databases.

**Comment by bdsmith147** [comment]
Hello there, I'm running into the same issues with the project. Do the free versions of both OSLO _and_ Zemax need to be installed on the computer? I have the OSLO EDU version, but it doesn't appear that Zemax is offering easily-accessible trial versions anymore. Is it possible to work with only the OSLO library? I'm running Windows 10.

Also, I wasn't sure about your directions for installing the libraries. In `\rayopt\`, do I create a `\catalog\` subdirectory, and then copy the OSLO library files to it? How do your directions change for Windows? I'm just not familiar with linux systems. Thank you!

**Comment by jamiklaucich** [comment]
Hey I ran into the same problem and managed to get it working with my particular setup on anaconda, not sure if it will be exactly the same for you.

You can use the Zemax optics studio link to download and install optics studio and the necessary catalogs (You have to run optics studio once until it asks you for a activation key then you can just close it).

I then opened the anaconda cmd.exe prompt and input  "python -m rayopt.library \ Users/$USER/Documents/Zemax/Glasscat \ Users/$USER/Documents/Zemax/Stockcat" (With $USER replaced with the name of your account) although I had to take out "INFRARED.agf" and "LACROIX.agf" from the "Glasscat" folder as it kept giving me an error while trying to add them.

Same process for the OSLO catalogs
